# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  
  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.synced_folder "../terracota", "/vagrant", type: "nfs", mount_options: ['nolock', 'vers=3', 'udp', 'noatime', 'actimeo=1']
  config.bindfs.bind_folder "/vagrant", "/vagrant",
    perms: "u=rwX:g=rD:o=rD",
    create_as_user: true


  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.name = "terracota-machine"
    # vb.gui = true
  end

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/terracota.yml"
  end
end
